services:
    orangegate.form.admin.choice:
        class: Symbio\OrangeGate\FormBundle\Admin\ChoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Form }
        arguments:
            - ~
            - Symbio\OrangeGate\FormBundle\Entity\Choice
            - ~
        calls:
            #- [setUserManager, [@fos_user.user_manager]]
            - [setTranslationDomain, [SymbioOrangeGateFormBundle]]

    orangegate.form.admin.field:
        class: Symbio\OrangeGate\FormBundle\Admin\FieldAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Form }
        arguments:
            - ~
            - Symbio\OrangeGate\FormBundle\Entity\Field
            - ~
        calls:
            #- [setUserManager, [@fos_user.user_manager]]
            - [setTranslationDomain, [SymbioOrangeGateFormBundle]]
            - [addChild, ['@orangegate.form.admin.choice']]

    orangegate.form.admin.form:
        class: Symbio\OrangeGate\FormBundle\Admin\FormAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Form }
        arguments:
            - ~
            - Symbio\OrangeGate\FormBundle\Entity\Form
            - ~
        calls:
            #- [setUserManager, [@fos_user.user_manager]]
            - [setTranslationDomain, [SymbioOrangeGateFormBundle]]
            - [addChild, ['@orangegate.form.admin.field']]
